### ISSUE TITLE
Applications list based on call volume. 

### ISSUE THREAD

**Issue by Sravan921** [Appdynamics/AppDynamics.DEXTER#111]
Hey,
We have around 500 applications in AppD. Is there any way to pull the applications list based on load (calls) from the past three or six months? I only need call count and application name, nothing else. Could you please tell me the steps to get this data ?

Thanks,
Sravan

**Comment by danielodievich** [comment]
**Now:**
Target with Type=APM
ApplicationName=.*
NameRegex=true

Input\DetectedEntities=true
Input\Metrics=true
Input\MetricSelectionCriteria="TransactionApplication"

Output\DetectedEntities=true
Output\Metrics=true

Specify timeframe you want

Everything else to false

It will take a long time as it extracts hourly chunks but it'll get done

**In the next release:**
Target with Type=APM
ApplicationName=.*
NameRegex=true

Input\DetectedEntities=true
Input\Metrics=true
Input\"MetricsSelectionCriteria": {
            "MetricSets": [ "TransactionApplication"],
            "IncludeHourAndMinuteDetail": false
        },

Output\DetectedEntities=true
Output\Metrics=true

Specify timeframe you want

Everything else to false
This will be incredibly fast.
Not available for probably another 2 weeks

**Comment by Sravan921** [comment]
Thank you so much for the prompt response. I do have a question regarding the time frame. 

Let's say if I want to get the data from the past 3 months ? what values do I need to use?

 I don't see any attribute for the end date.  

 "MarkDate": "TODAY",
            "MarkTime": "PREVIOUS_HOUR",
            "Duration": "1:00:00"

**Comment by danielodievich** [comment]
https://github.com/Appdynamics/AppDynamics.DEXTER/wiki/Job-File#timeframe makes it pretty easy

You specify when you want to start or end via MarkDate/MarkTime. You specify duration in Duration. If your MarkDate/MarkTime is start date, duration is positive, otherwise it is negative.

Say you want April, May and June and you want to start in the beginning. These will be all equivalent:
"MarkDate": "2020-05-1",
"MarkTime": "00:00:00",
"Duration": "90.0:00:00"
or 
"MarkDate": "2020-05-1",
"MarkTime": "00:00:00",
"Duration": "P3M"
or 
"MarkDate": "2020-05-1",
"MarkTime": "00:00:00",
"Duration": "P90D"
