### ISSUE TITLE
Snapshot collect filter by BT name

### ISSUE THREAD

**Issue by juantimonescalona** [Appdynamics/AppDynamics.DEXTER#4]
Hi Daniel
I am using Dexter for extract snapshots and other metrics, in a customer with 40 millions of call per day in the main application.
I have a problem for extract the snapshots in this big application, because in the first step of Dexter process, when collect data from Controller, download all snapshots in the application, don´t use filters "SnapshotSelectionCriteria/BusinessTransactions"
I see the Api documentation for version 4.5: https://docs.appdynamics.com/display/PRO45/Metric+and+Snapshot+API
It´s possible use this filter: "business-transaction-ids" for accelerate the proccess, and filter the snapshot extraction by BT

Regards

**Comment by danielodievich** [comment]
Hello Juan,

The tool does not use public API to get list of Snapshots because it does not allow retrieval of more than 600 snapshots and does not support paging.

The private API may allow me to filter the snapshots in advance, but I chose not to do it. Instead I download the full list and filter it after download. This SHOULD be working with the SnapshotSelectionCriteria/BusinessTransactions selector.

Daniel

**Comment by danielodievich** [comment]
Works as designed
