### ISSUE TITLE
Invalid Certificates are preventing DEXTER from accessing Controller on .NET Core builds

### ISSUE THREAD

**Issue by danielodievich** [Appdynamics/AppDynamics.DEXTER#65]
DEXTER is built to ignore certificate validation errors.
The check to ignore does not work on .NET Core builds
Needs to be fixed

Discovered by @kozyrenko

**Comment by danielodievich** [comment]
Fixed in 68f8fd0425a029a626231536de019428bc8835fe already, but need to build and release

**Comment by sara-ng** [comment]
Hi Daniel,
I have been hitting incorrect password/username error running on linux box, a check in the logs show the below, is this due to this bug? if so, when will this be released?

The SSL connection could not be established, see inner exception.) ---> System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception. ---> System.Security.Authentication.AuthenticationException: The remote certificate is invalid according to the validation procedure.

**Comment by danielodievich** [comment]
Hello Sara,

The certificate for your Controller is clearly not trusted by the machine you are running DEXTER from. This is exactly what should happen with untrusted certificate. However, I built DEXTER to ignore certificate validation failures. Unfortunately, changes between .NET Core 2.1 and the current version of .NET Core 2.2 invalidated my checks. You can see in the comment as of 2 days ago, I already found and fixed that, but I have not released the fix into the wide availability.

One simple workaround as of right now is to run a .net full framework build (full-win folder) which has a valid ignore procedure for certificate errors. You would only be able to run it on Windows only. 

Second, more complicated workaround is to force your OS to trust the certificate somehow. I know how to do that in Windows, but not on Linux. A quick search on the net shows things like https://unix.stackexchange.com/questions/90450/adding-a-self-signed-certificate-to-the-trusted-list.

Third workaround is to wait until I release the next build, which I wasn't planning for a while but can be persuaded to do soon

**Comment by danielodievich** [comment]
I released https://github.com/Appdynamics/AppDynamics.DEXTER/releases/tag/1.2.40.0 with this fix
